# Repeat standard config options
baseurl: "https://hackshackers.com/"
enableEmoji: true
ignoreFiles: [ "README\\.md$" ]
languageCode: "en-us"
title: "Hacks/Hackers"
theme: "hackshackers-2017"
disableRSS: true
disableSitemap: true

# Dev-specific config options
# Revert for production use
contentDir: "content"
dataDir: "content/data"

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"

menu:
  main:
    - Name: About
      URL: "/about/"
    - Name: Find A Group
      URL: "/groups/"
    - Name: Featured Events
      URL: "/featured-events/"
    - Name: Resources
      URL: "/resources/"
    - Name: Blog
      URL: "/blog/"

params:
  twitter: HacksHackers
  facebook: HacksHackers
  tagline: join the media revolution
  subtagline: rebooting journalism
  og_image:
    url: "https://hackshackers.com/images/hh_logo_stacked.jpg"
    width: 920
    height: 365
  og_desc: One or two sentences describing Hacks/Hackers. Those go here.
  events:
    homepage: 5
    credit: "Events feed courtesy of [Peter MacRobert](https://twitter.com/PeteM) / [Matchmaker](https://matchmaker.hhldn.co.uk/welcome)"
