# Repeat standard config options
baseurl: "https://hackshackers.com/"
enableEmoji: true
ignoreFiles: [ "README\\.md$" ]
languageCode: "en-us"
title: "Hacks/Hackers"
theme: "hackshackers-2017"
disableRSS: true
disableSitemap: true

# Dev-specific config options
# Revert for production use
contentDir: "sample-content"
dataDir: "sample-content/data"

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
